// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-ObxgwGd5URam26Gj8JzNd-zXTJLHI9Q',
    appId: '1:298352581096:web:1acab0d5c6a5b6e84d6c5d',
    messagingSenderId: '298352581096',
    projectId: 'auth-screens-f835b',
    authDomain: 'auth-screens-f835b.firebaseapp.com',
    storageBucket: 'auth-screens-f835b.appspot.com',
    measurementId: 'G-EW9T84KK4B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGnYUeZeUjNa17VIpztqo01ZFCohyhiAk',
    appId: '1:298352581096:android:1da8e381c22a47954d6c5d',
    messagingSenderId: '298352581096',
    projectId: 'auth-screens-f835b',
    storageBucket: 'auth-screens-f835b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgdgQbSEBbeanahK9UiBX9p1NogQFN7-Q',
    appId: '1:298352581096:ios:5c2128ac159014a94d6c5d',
    messagingSenderId: '298352581096',
    projectId: 'auth-screens-f835b',
    storageBucket: 'auth-screens-f835b.appspot.com',
    iosBundleId: 'com.example.authScreensFlutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgdgQbSEBbeanahK9UiBX9p1NogQFN7-Q',
    appId: '1:298352581096:ios:1edf2771b40f202b4d6c5d',
    messagingSenderId: '298352581096',
    projectId: 'auth-screens-f835b',
    storageBucket: 'auth-screens-f835b.appspot.com',
    iosBundleId: 'com.example.authScreensFlutterFirebase.RunnerTests',
  );
}
